[package]
name = "diatypst"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["skriptum (https://github.com/skriptum)"]
license = "MIT-0"
description = "easy slides in typst - sensible defaults, easy syntax, well styled"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "screenshots/Thumbnail.png"